Repository variety-crew/brewnet-web, pull requests merged in 2024-12, with the labels that each got.

#116 [PURCHASE] 구매품의서 삭제(결재 요청 취소) api 연동
  src/utils/api/HQPurchaseApi.js
  src/views/headQuarter/PurchaseDetailView.vue
Labels: enhancement

#117 Feat/export excel
  src/utils/ExcelManager.js
  src/utils/api/FCOrderApi.js
  src/utils/api/HQExchangeTempApi.js
  src/utils/api/HQFranchiseApi.js
  src/utils/api/HQOrderApi.js
  src/utils/api/HQReturnTempApi.js
  src/views/franchise/OrderListView.vue
  src/views/headQuarter/ExchangeListView.vue
  src/views/headQuarter/FranchiseListView.vue
  src/views/headQuarter/OrderListView.vue
Labels: enhancement

#118 [STORAGE] 창고별 상품 재고 조정 api 연동
  src/components/headQuarter/ChangeStockModalBody.vue
  src/utils/api/HQStorageApi.js
  src/views/headQuarter/StockListByStorageView.vue
Labels: enhancement

#119 Feat/api/item
  src/components/common/AppTable.vue
  src/components/common/form/AppInputNumber.vue
  src/components/common/form/AppSelect.vue
  src/components/headQuarter/AddItemCategoryModalBody.vue
  src/components/headQuarter/ItemCategoryGroup.vue
  src/components/headQuarter/ItemCategoryList.vue
  src/utils/api/CategoryApi.js
  src/utils/api/HQItemApi.js
  src/utils/api/ItemApi.js
  src/utils/helper.js
  src/views/headQuarter/ItemCategoryView.vue
  src/views/headQuarter/ItemFormView.vue
  src/views/headQuarter/ItemListView.vue
Labels: enhancement

#120 [PURCHASE] 구매품의서 출력 기능 추가
  src/components/headQuarter/PrintPurchasePdfPreviewModal.vue
  src/utils/api/HQPurchaseApi.js
  src/views/headQuarter/PurchaseDetailView.vue
  src/views/headQuarter/StockListByStorageView.vue
Labels: enhancement

#121 Feat/hq/dashboard
  package-lock.json
  package.json
  src/components/headQuarter/DashboardCalendarCard.vue
  src/components/headQuarter/DashboardChartCard.vue
  src/components/headQuarter/DashboardMyApprovalWaitCard.vue
  src/components/headQuarter/DashboardNewOrderCard.vue
  src/components/headQuarter/DashboardSafetyStockCard.vue
  src/components/headQuarter/DashboardTable.vue
  src/components/headQuarter/HeadQuarterPageBody.vue
  src/components/headQuarter/PageTitle.vue
  src/hooks/useDraftNavigation.js
  src/utils/api/HQStatisticsApi.js
  src/views/headQuarter/HomeView.vue
  src/views/headQuarter/MyApprovalView.vue
  src/views/headQuarter/MyDraftView.vue
Labels: enhancement

#122 Feat/print pdf
  src/components/franchise/OrderDetailTable.vue
  src/components/franchise/PrintOrderPdfPreviewModal.vue
  src/components/headQuarter/PrintOrderPdfPreviewModal.vue
  src/utils/constant.js
  src/views/franchise/OrderDetailView.vue
  src/views/headQuarter/OrderDetailView.vue
Labels: enhancement

#125 [PURCHASE] 발주서 외부용/내부용 출력 기능
  src/components/headQuarter/PrintInHouseDocumentPreviewModal.vue
  src/components/headQuarter/PrintPurchaseDocumentPreviewModal.vue
  src/components/headQuarter/PrintPurposeModalBody.vue
  src/utils/api/HQPurchaseApi.js
  src/utils/format.js
  src/views/headQuarter/PurchaseDetailView.vue
Labels: enhancement

#126 Feat/must buy
  src/components/common/LoadingSpinner.vue
  src/components/common/form/AppDatePicker.vue
  src/components/headQuarter/AddMustBuyItemModalBody.vue
  src/hooks/useModal.js
  src/router/AppMenu.js
  src/router/router.js
  src/utils/api/FCItemApi.js
  src/utils/api/HQItemMustBuyApi.js
  src/views/franchise/OrderFormView.vue
  src/views/headQuarter/ItemMustBuyListView.vue
  src/views/headQuarter/OrderListView.vue
Labels: enhancement

#129 fix: 발주 품목 입고 처리 페이지네이션 수정
  src/views/headQuarter/PurchaseStockArrivalListView.vue
Labels: enhancement

#132 Feat/return
  src/components/common/AppLabel.vue
  src/components/common/AppLabelText.vue
  src/components/common/AppTableStyled.vue
  src/components/common/form/AppChooseFileList.vue
  src/hooks/useFiles.js
  src/router/router.js
  src/utils/FileUtil.js
  src/utils/api/FCReturnApi.js
  src/utils/api/HQReturnApi.js
  src/utils/constant.js
  src/utils/format.js
  src/utils/helper.js
  src/views/franchise/ReturnDetailView.vue
  src/views/franchise/ReturnFormView.vue
  src/views/franchise/ReturnListView.vue
  src/views/headQuarter/NoticeFormView.vue
  src/views/headQuarter/ReturnListView.vue
Labels: enhancement

#158 Fix/delivery screen
  components.d.ts
  src/App.vue
  src/components/common/AppConfirmModal.vue
  src/components/delivery/DeliveryList.vue
  src/stores/notification.js
  src/views/DeliveryIndexView.vue
  src/views/delivery/DetailView.vue
  src/views/delivery/ExchangeReturnView.vue
  src/views/delivery/HomeView.vue
Labels: question

#160 Feat/hq search filter
  package-lock.json
  src/App.vue
  src/components/common/AppLabel.vue
  src/components/common/AppLabelText.vue
  src/components/common/AppNavbar.vue
  src/components/common/AppTable.vue
  src/components/common/AppTableStyled.vue
  src/components/common/SideMenuBar.vue
  src/components/common/form/AppDateRangePicker.vue
  src/components/common/form/AppInputPassword.vue
  src/components/delivery/DeliveryList.vue
  src/components/franchise/FranchiseTopBar.vue
  src/components/headQuarter/HeadQuarterPageBody.vue
  src/components/headQuarter/HeadQuarterTopBar.vue
  src/utils/api/FCOrderApi.js
  src/utils/api/HQOrderApi.js
  src/views/auth/LoginView.vue
  src/views/franchise/OrderListView.vue
  src/views/headQuarter/OrderListView.vue
  src/views/headQuarter/PurchaseDetailView.vue
  src/views/headQuarter/PurchaseFormView.vue
  src/views/headQuarter/PurchaseListView.vue
Labels: enhancement

#161 Feat/return exchange/add filter
  src/utils/api/HQExchangeApi.js
  src/utils/api/HQPurchaseApi.js
  src/utils/api/HQReturnApi.js
  src/views/headQuarter/ExchangeListView.vue
  src/views/headQuarter/PurchaseListView.vue
  src/views/headQuarter/ReturnListView.vue
Labels: enhancement

#162 Fix/order invoice
  index.html
  src/App.vue
  src/assets/base.css
  src/utils/constant.js
  src/views/headQuarter/OrderDetailView.vue
Labels: bug

#163 V1/develop
  index.html
  src/assets/base.css
  src/utils/constant.js
  src/views/headQuarter/OrderDetailView.vue
Labels: bug

#164 Fix/dashboard
  src/components/headQuarter/DashboardCalendarCard.vue
  src/components/headQuarter/DashboardChartCard.vue
  src/components/headQuarter/DashboardMonthOrderGraphCard.vue
  src/components/headQuarter/DashboardMyApprovalWaitCard.vue
  src/components/headQuarter/DashboardNewOrderCard.vue
  src/components/headQuarter/DashboardSafetyStockCard.vue
  src/views/headQuarter/HomeView.vue
Labels: bug

#165 V1/develop
  src/components/common/AppTable.vue
  src/components/franchise/FranchisePageBody.vue
  src/components/franchise/FranchiseTopBar.vue
  src/components/franchise/SelectItemTable.vue
  src/components/headQuarter/CorrespondentItemTable.vue
  src/components/headQuarter/DashboardMonthOrderGraphCard.vue
  src/components/headQuarter/HeadQuarterPageBody.vue
  src/components/headQuarter/HeadQuarterTopBar.vue
  src/router/AppMenu.js
  src/router/router.js
  src/stores/user.js
  src/utils/PrintPDFManager.js
  src/utils/constant.js
  src/utils/helper.js
  src/views/DeliveryIndexView.vue
  src/views/franchise/ExchangeFormView.vue
  src/views/franchise/OrderDetailView.vue
  src/views/franchise/OrderFormView.vue
  src/views/franchise/OrderListView.vue
  src/views/franchise/ReturnFormView.vue
  src/views/headQuarter/ApprovalLineView.vue
  src/views/headQuarter/CompanyInfoView.vue
  src/views/headQuarter/CompanySealView.vue
  src/views/headQuarter/EmployeeFormView.vue
  src/views/headQuarter/EmployeeListView.vue
  src/views/headQuarter/FranchiseListView.vue
  src/views/headQuarter/HomeView.vue
  src/views/headQuarter/NoticeListView.vue
Labels: bug
